### ISSUE TITLE
Find a way to read FASTA files and group the sequence

### ISSUE THREAD

**Issue by vmesel** [vmesel/FastaDB#1]
I need to find  a way to make the FDB read and check if the sequence is a DNA, RNA or Protein sequence.

Ways to do that:
- REGEX

**Comment by vmesel** [comment]
Regex doesn't work! We need some if else statements so we can get the raw sequences!

**Comment by ventsin** [comment]
C++ possible solution:

``` c++
#include <fstream>
#include <string>
#include <vector>

void main()
{
	std::vector<std::string> sequences;
	std::string currentSequence;
	
	std::ifstream file("test.fas");
	std::string line;
	
	while(std::getline(file, line))
	{
		size_t found = line.find('>');
		if(found != std::string::npos)
		{
			//this is a new sequence
			if(!currentSequence.empty())
			{
				sequences.push_back(currentSequence);
				current.clear;
			}
		}
		else
		{
			//this is the continuation of a sequence
			current += line;
		}
	}
	
	if(!currentSequence.empty())
	{
		sequences.push_back(currentSequence);
		currentSequence.clear();
	}
}
```

**Comment by kinow** [comment]
I think keeping the number of dependencies to a minimum is good. But in this case I'd point at [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), and suggest to use [BioPython](http://biopython.org/), since the project is written in Python.

Using BioPython as dependency won't have a negative effect on what users think about the project. On the contrary, I believe users would prefer that this part of the code (i.e. parsing Fasta files) was being handled by a well-tested code. Users that are familiar with BioPython could also suggest enhancements, or help investigating issues.

Lastly, should you find interesting new features that could be ported to BioPython, or maybe bugs in BioPython, you could submit them to the project. Helping not only FastaDB users, but also BioPython users. A win-win case (-:

Just my 0.02 centavos

**Comment by vmesel** [comment]
@kinow "toma aqui seus 2 cents" kkk... So, yeah, you got a very good point, I will use the BioPython lib so it can handle the fasta files easier than doing the code again, and since it's well known, the code could actually grow with them and, someday, become a part of the original core of the BioPython project.

**Comment by kinow** [comment]
Way to go @vmesel :-) In the meantime I'm watching the repo and can help testing it, providing feedback, etc.

**Comment by vmesel** [comment]
No problema @kinow, gotta install Visual Studio for handling the compiled C++ code in the lib. Then I'll test it!

**Comment by inaciomdrs** [comment]
"Fala Pessoal" Hi Folks. I've got interested in this problem of recognizing if read sequence is DNA, RNA or proteins. Ideia is relatively simple: if you get some "U" inside it, it can be RNA, if you get just A, T, C, G, it's DNA, otherwise it's protein. If you please, I can implement some code in python (and inclusive using some BioPython stuff) for solving this problem.

"No mais, vamos que vamos" So let's go!

**Comment by vmesel** [comment]
@inaciomdrs you rock! If you can do that, it would be great! The idea for detecting if its protein, DNA or RNA is pretty good, but I dont think it's needed for this first release version! We need to get our FASTA file assets and convert to the JSON scheme showed in the About.md!
Maybe, we can use the DNA/RNA/Protein thing in a future way to query data around, it would be awesome! If you need help, just reply to this issue! Please fork and do the changes you think are good for the project. "Nois que avoa bruxão kkk" Lets get started!

**Comment by inaciomdrs** [comment]
@vmesel "Xá com nós, mermão kkkkkkk" Let's do it! Convert to JSON scheme also won't be a "very difficult challenge", we're can do it fast too. Let's go!

**Comment by vmesel** [comment]
@inaciomdrs I've done the bioPython integration! I need you to put this info on the FDB file format like shown in the README.md! Please do a git pull in your local repo!

**Comment by inaciomdrs** [comment]
@vmesel Roger that dude, pulling right now!

**Comment by inaciomdrs** [comment]
@vmesel I'm looking at fdb.py, this Bio.SeqIO is from BioPython, right? Also, were created some irc chanell for this project, as you've commented on reddit?

**Comment by inaciomdrs** [comment]
Good Evening folks. I've just implemented an initial version for "json parsing" functionality. It's available [over here](https://github.com/inaciomdrs/FastaDB/blob/bug_fixes_and_json_parsing/FastaDB/fdb.py), check it out!

A problem that I've got with it (and need help for solving) is the following: it works fine in python3, prints everything, but in python2 it doesn't print almost anything. Also, when I run flake8, It accuses "test:1:1: E902 IOError: [Errno 2] No such file or directory: 'test'".

All of these (and others) modifications are in [this branch](https://github.com/inaciomdrs/FastaDB/tree/bug_fixes_and_json_parsing).

**Comment by vmesel** [comment]
@inaciomdrs could you make it available in a pull request! Them we will start working on the core of the queries!

**Comment by inaciomdrs** [comment]
Sure yeah @vmesel! Looking now at repo, you've already done that, right?

**Comment by vmesel** [comment]
Fasta files are readable now! Awesome!
Closing this issue, reopen only if needed!
